export const tournamentsData = [
  {
    id: 1,
    label: 'Registering',
    isPin: true,
    type: 'NL 2-7 Triple Draw',
    tags: [],
    title: 'OFC Pineapple',
    isColorTitle: false,
    date: '12:00 pm, 28 July',
    players: '1000/1000',
    tourney: '1000000',
  },
  {
    id: 2,
    label: 'Registering',
    isPin: true,
    type: 'NL Holdem',
    tags: [],
    title: 'OFC Pineapple',
    isColorTitle: true,
    date: '12:00 pm, 28 July',
    players: '1/6',
    tourney: '100',
  },
  {
    id: 3,
    label: 'Canceled',
    isPin: true,
    type: 'NL OFC/pineapple prg',
    tags: ['time', 'freeRoll'],
    title: 'Hourly Freeroll',
    isColorTitle: false,
    date: '12:00 pm, 28 July',
    players: '1/10 000',
    tourney: '1000',
  },
  {
    id: 4,
    label: 'Canceled',
    isPin: false,
    type: 'PL Omaha h/l',
    tags: [],
    title: 'Rapid Tournament',
    isColorTitle: false,
    date: '12:00 pm, 28 July',
    players: '0/0',
    tourney: '1000000',
  },
  {
    id: 5,
    label: 'Canceled',
    isPin: false,
    type: 'NL 6 cards omaha h/l',
    tags: ['rapid'],
    title: 'PL Omaha Knockout',
    isColorTitle: false,
    date: '12:00 pm, 28 July',
    players: '0/100',
    tourney: '146',
  },
  {
    id: 6,
    label: 'Registering',
    isPin: false,
    type: 'NL 2-7 Triple Draw',
    tags: [],
    title: 'OFC Pineapple',
    isColorTitle: true,
    date: '12:00 pm, 28 July',
    players: '1000/1000',
    tourney: '1000000',
  },
];
